### ISSUE TITLE
Cannot reproduce the BERT results

### ISSUE THREAD

**Issue by mldwr** [ashokc/Bow-to-Bert#6]
Hi,
I've migrated the TF1 code to TF2 https://github.com/mldwr/Bow-to-Bert_TF2
However, I get totally weired results, but I can reproduce the fasttext result on spot. 

Here is an example:
record the play  <=>  play the record                   <=>  0.998
record the play  <=>  play the game                     <=>  0.973
play the record  <=>  play the game                     <=>  0.968

arms bend at the elbow  <=>  germany sells arms to saudi arabia                         <=>  0.935
arms bend at the elbow  <=>  wave your arms around                      <=>  0.862
germany sells arms to saudi arabia  <=>  wave your arms around                  <=>  0.944

the problem has no solution  <=>  boil the solution with salt                   <=>  0.973
the problem has no solution  <=>  heat the solution to 75 degrees                       <=>  0.826
boil the solution with salt  <=>  heat the solution to 75 degrees                       <=>  0.81

all income is subject to tax  <=>  economics an arts subject                    <=>  0.929
all income is subject to tax  <=>  i have one subject for credit                        <=>  0.919
economics an arts subject  <=>  i have one subject for credit                   <=>  0.876

the key issue is quality not quantity  <=>  the key broke in the lock                   <=>  0.645
the key issue is quality not quantity  <=>  i lost my key                       <=>  0.681
the key broke in the lock  <=>  i lost my key                   <=>  0.819

**Comment by mldwr** [comment]
I've uploaded my bertWordVectors file here: https://github.com/mldwr/Bow-to-Bert_TF2/blob/master/bertWordVectors.jsonl

**Comment by ashokc** [comment]
Hi Maldewar - I downloaded your jsonl file and verified what you show above. Weird indeed & a good find!

I still had the old TF1.x vectors I generated back then. For what it is worth I uploaded them here.

[https://github.com/ashokc/Bow-to-Bert/blob/master/bertWordVectors.jsonl](https://github.com/ashokc/Bow-to-Bert/blob/master/bertWordVectors.jsonl)

And it gives the numbers reported in the article.

I need to redo this exercise with the latest TF and see what gives.

Ashok

**Comment by mldwr** [comment]
Hey Ashok, thanks for the quick reply and the vectors file.
With that file I could reproduce your results. Nice! :)

I've also compared these sentences with other models like roberta, bert-uncased, mpnet and minilm (uploaded to my repo as results_*.out files).
They all can find the correct relation except for the one example "record the play" and "play the record". 

I'll also try to investigate the deviation in the TF1 and TF2 versions as well. 

Regards,
Maldewar

**Comment by ashokc** [comment]
Hi Maldewar,

Did a quick implementation of this using the current Huggingface 'transformers' module & pytorch, and using the same 12-768-Lcase pretrained-bert model.

The results are consistent meaning, a word is more parallel to the same word used in a different sentence but used in a similar vein. Contextual similarity.

Of course we are using the dot product to measure similarity, but other measures like euclidean, manhattan distances can be tried as well...

The actual dot product 'numbers' are different of course which is expected. Here is the output from my run.

I will push my code out to different repo after some clean-up, in case it may be useful to some.

Test Word:arms
germany sells arms to saudi arabia  <=>  arms bend at the elbow 		<=>  0.378
**arms bend at the elbow  <=>  wave your arms around 		<=>  0.498**
wave your arms around  <=>  germany sells arms to saudi arabia 		<=>  0.422


Test Word:solution
the problem has no solution  <=>  boil the solution with salt 		<=>  0.448
**boil the solution with salt  <=>  heat the solution to 75 degrees 		<=>  0.861**
heat the solution to 75 degrees  <=>  the problem has no solution 		<=>  0.538


Test Word:subject
all income is subject to tax  <=>  economics is an arts subject 		<=>  0.332
**economics is an arts subject  <=>  i have one subject for credit 		<=>  0.617**
i have one subject for credit  <=>  all income is subject to tax 		<=>  0.347


Test Word:key
the key issue is quality not quantity  <=>  the key broke in the lock 		<=>  0.391
**the key broke in the lock  <=>  i lost my key 		<=>  0.577**
i lost my key  <=>  the key issue is quality not quantity 		<=>  0.32


Test Word:play
record the play  <=>  play the record 		<=>  0.367
**play the record  <=>  play the game 		<=>  0.502**
play the game  <=>  record the play 		<=>  0.478

Ashok

**Comment by mldwr** [comment]
Hi Ahsok,
thank you for these really nice results! :)
Would be great, if you could upload the code.
Thanks

**Comment by mldwr** [comment]
I think this issue can be considered as resolved.

**Comment by ashokc** [comment]
Here is the link to the repo with the updated code, maldewar.

[Context Aware Word Vectors](https://github.com/ashokc/context-aware-word-vectors)
